### ISSUE TITLE
Absolute names with relative search origin

### ISSUE THREAD

**Issue by pprocacciHome** [zostay/raku-IO-Glob#19]
"Using an absolute glob with a relative search origin is not permitted."

Why is this?  perl5 allows for the following:

`for glob("/home/user/.something/blah/*/*/*.yaml"){ }`

Yet, perl6 (or raku) if you prefer doesn't.

I don't know the reasons behind this, nor the difficulty in making a function with glob as its name fully support globbing but it'd be a nice thing to have.

**Comment by zostay** [comment]
Use:

```perl6
for glob("/home/user/.something/blah/*/*/*.yaml").dir("/") { }
```

The issue is that the call to `.dir()` is implicit and it assumes the current working directory if no directory is given.

**Comment by zostay** [comment]
If you feel it's a bug, feel free to submit a PR. It probably wouldn't be too complicated.

**Comment by pprocacciHome** [comment]
I'm sorry.  "If I feel it's a bug"?  It certainly _is_ a bug otherwise I wouldn't have filed this issue which you've kindly closed.  Not only is this certainly a bug,

- this module not handling '~/something' either is also a bug.  
- this module not handling 'something/////////*.log' is also a bug
- this module not handling '/something' is a bug.

You know who gets this right?  perl 5, python, php .... and probably others. 

Perl 6 has inherited a "just do the right thing" type of mentality yet this module is anything but "doing the right thing".  It's ignoring shell semantics that end users like myself _expect_ from a glob routine.

**Comment by zostay** [comment]
I gave you the designed solution for this problem. It was designed to work this way. If you want to add the feature to make it work a different way, then add it and I will consider it.
